### ISSUE TITLE
Got unexpected status code 401 (Unauthorized).

### ISSUE THREAD

**Issue by tvvocold** [ImmobilienScout24/yum-repo-client#14]
I have set the yum repo server up(in a pubilc ip:8080) and installed client. 
When i run 
$repoclient create test --hostname 120.132.ip.ip --port 8080 
I got http://p.fdzh.org/paste/YWVQXgGe
How to fix?(How to get authorize/add a authorized user?)

**Comment by tvvocold** [comment]
i  add "pam.service.name=mypasswords-auth" in /opt/tomcat/webapps/ROOT/WEB-INF/classes/configuration.properties and restart tom but it won't work.

**Comment by mriehl** [comment]
The repoclient will not authenticate by default. Only if you add the --username flag.
It will then also prompt for a password.

**Comment by tvvocold** [comment]
OK, so the user name is "auth" ?

**Comment by mriehl** [comment]
Nope, the user name is any valid user name you have on the server. The password is then the matching password for this user.

There is no user in the app itself, it's all done through the PAM library.

**Comment by tvvocold** [comment]
OK, where can i add a vaild user name and set password?

**Comment by mriehl** [comment]
On the server.. You could use one that is already there or create one with useradd.

http://linux.die.net/man/8/useradd

**Comment by tvvocold** [comment]
So the server is using the Linux's user?
I try  $repoclient create hello --hostname 120.132.ip.ip --port 8080 -u root
then type mypasswords-auth, but it doesn't work.
either do root's password.

**Comment by mriehl** [comment]
What is mypasswords-auth? Changing the pam service name is only useful if you replace the placeholder ;-)
The pam service you have configured in the configuration.properties should let you authenticate with the username you're using. I suggest leaving the pam service name as it is by default and creating a service user and using that.

**Comment by tvvocold** [comment]
So can i just need to delete the "pam.service.name=password-auth" in configuration.properties and add/use a nonroot user?
Thx,btw.

**Comment by mriehl** [comment]
Just create more linux system users - ideally keep their privileges to a minimum. You can use useradd for this.

**Comment by tvvocold** [comment]
Many thx!
